### ISSUE TITLE
Variables with Numbers are not converted correctly 

### ISSUE THREAD

**Issue by rrdlpl** [finntenzor/change-case#9]
formatName("AWS_S3_BUCKET_NAME", "PascalCase")

=> AwsSBucketName

Expected output 

=> AwsS3BucketName

**Comment by finntenzor** [comment]
I forgot the case of variables with numbers. The state machine is not complete. I am preparing to fix this problem, but unfortunately it may not be finished until around February 24th.

**Comment by finntenzor** [comment]
It's going better than I expected, and seems to have been fixed in version 0.0.5.
